sudo: required

notifications:
  email: false

branches:
  only:
  - master
  - development

matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip3: true
      install:
        - pip3 install django
        - pip3 install django-bootstrap3
      before_script:
        - python3 manage.py makemigrations
        - python3 manage.py migrate
      script:
        - python3 manage.py test
